### ISSUE TITLE
포토 상세에서 평가 정보도 내려줘야함.

### ISSUE THREAD

**Issue by YeomJaeSeon** [dungLab/face-backend#9]
-> 몇명이 봣고 몇명이 좋아요 했는지 노출.

- 평가 완료되엇을떄만?
- 아니면 평가 중인것에도?

@sooohka

**Comment by YeomJaeSeon** [comment]
@sooohka 
평가중인데도 본인은 볼수있게하는거죠?

**Comment by sooohka** [comment]
> @sooohka 
> 
> 평가중인데도 본인은 볼수있게하는거죠?

재선님생각은 어떠신가요?

**Comment by YeomJaeSeon** [comment]
> > @sooohka
> > 평가중인데도 본인은 볼수있게하는거죠?
> 
> 재선님생각은 어떠신가요?

보여주는게 더 사용자로하여금 계속해서 저희 서비스 사용할수있게 할거 같네요 @sooohka
